version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./.htpasswd:/etc/nginx/.htpasswd
  openhab-auth-router:
    image: hendrikmaus/openhab-auth-router:local
    command: 'openhab-auth-router -host="0.0.0.0" -port="80" -target="http://openhab" -config="/usr/share/config.yaml" -log-level="debug" -log-type="human"'
    ports:
    - 9090:80
    volumes:
    - ./config.yaml:/usr/share/config.yaml
  openhab:
    image: "openhab/openhab:2.3.0-amd64-debian"
    restart: always
    command: "./start_debug.sh"
    tty: true
    environment:
      OPENHAB_HTTP_PORT: "80"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
    ports:
    - 8080:80