name: end-to-end-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget -O wait-for-it https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it
      - run: |
          cd testing
          ./test.sh
